import type { Metadata } from "next";
import { Geist, Geist_Mono, Ubuntu } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const trap = localFont({
  src: [
    {
      path: "./fonts/Trap-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/Trap-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Trap-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Trap-SemiBold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Trap-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Trap-ExtraBold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Trap-Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-trap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${trap.variable}  ${geistSans.variable} ${geistMono.variable}`}
    >
      <body className={`${trap.className} antialiased min-h-screen mx-auto`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
